### ISSUE TITLE
Error where it states audio file is not present, but it is present. help

### ISSUE THREAD

**Issue by AMX0013** [Eduardovasquezn/ai-voice-assistant#1]
Finished chain.
Recording...
Writing...
Transcribing...
Current directory files: ['.env', '.gitignore', '.venv', 'LICENSE', 'README.md', 'requirements.txt', 'src', 'temp_audio_chunk.wav']
Current directory files: ['.env', '.gitignore', '.venv', 'LICENSE', 'README.md', 'requirements.txt', 'src', 'temp_audio_chunk.wav'] temp_audio_chunk.wav True
2024-07-27 20:32:07.065 Uncaught app exception
Traceback (most recent call last):

Traceback (most recent call last):
  File "D:\Github\Sales_AI_agent\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "D:\Github\Sales_AI_agent\src\app.py", line 56, in <module>
    main()
  File "D:\Github\Sales_AI_agent\src\app.py", line 31, in main
    text = transcribe_audio(model, chunk_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Github\Sales_AI_agent\.\src\utils.py", line 77, in transcribe_audio
    results = model.transcribe(file_path , fp16=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Github\Sales_AI_agent\.venv\Lib\site-packages\whisper\transcribe.py", line 122, in transcribe
    mel = log_mel_spectrogram(audio, model.dims.n_mels, padding=N_SAMPLES)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Github\Sales_AI_agent\.venv\Lib\site-packages\whisper\audio.py", line 140, in log_mel_spectrogram
    """

  File "D:\Github\Sales_AI_agent\.venv\Lib\site-packages\whisper\audio.py", line 58, in load_audio
    # Delete next line as not part of the lib
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by jaid-monwar** [comment]
Same issue here. @AMX0013 could you solve it? @Eduardovasquezn can you please help to fix this bug.

**Comment by AMX0013** [comment]
I fixed it! I downloaded the ffmpeg stuff and put the point variablt to that file itself C:Users/programfiles/ffmpeg/bin/ffmpeg.exe

**Comment by jaid-monwar** [comment]
@AMX0013 I already have ffmpeg installed in my environment. What modifications did you have to do in his code to make it work? And are there any more libraries I need to install other than ffmpeg?

**Comment by AMX0013** [comment]
> @AMX0013 I already have ffmpeg installed in my environment. What modifications did you have to do in his code to make it work? And are there any more libraries I need to install other than ffmpeg?

PATH variable in system variable, add the path to the .exe directly. I learned it from chatgpt analyzing the error log. 


ffmpeg thing, it is not a pip install. it's a windows file too. So make sure its the windows thing that youre using

**Comment by jaid-monwar** [comment]
@AMX0013 yeess thank you! It started working fine now.
